language: node_js
sudo: false
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: fncVPxVcT7BGK3IJex0DaLU5PbND8dBVKzXG46CpPnQIG1aAJ3/M64CHWSzXf/gS+DtE0cd7TQSdR96+pPR7GkptwJD7jjEKTluXUTJ6Q5Q5KmN+WLrEMxA5F0ziNFlkupNoRHkmGJKFsJqNRn6GONxA/0c9rFQlcxH9JkqlqL8=
  file:
    - 'flesch-kincaid.js'
    - 'flesch-kincaid.min.js'
  on:
    tags: true
